version: "3.4"
services:
  beacon-chain:
    image: beacon-chain.erigon-caplin-gnosis.dnp.dappnode.eth:1.0.0
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v5.3.0
    volumes:
      - beacon-data:/root/.lighthouse
    ports:
      - 29005:29005/tcp
      - 29004:29004/udp
      - 30405:30405/tcp
      - 42069:42069/tcp
      - 42069:42069/udp
      - 30405:30405/udp
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      DEBUG_LEVEL: info
      BEACON_API_PORT: 3500
      CORSDOMAIN: http://lighthouse-gnosis.dappnode
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
      P2P_PORT: 29004
      TCP_P2P_PORT: 29005
      HTTP_ENGINE: ""
      NODE_TYPE: Minimal
  validator:
    image: validator.lighthouse-gnosis.dnp.dappnode.eth:1.0.0
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v5.3.0
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      DEBUG_LEVEL: info
      HTTP_WEB3SIGNER: http://web3signer.web3signer-gnosis.dappnode:9000
      BEACON_NODE_ADDR: http://beacon-chain.lighthouse-gnosis.dappnode:3500
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-data: {}
